version: 2

project_name: jailoc

before:
  hooks:
    - npm install
    - npm run build
    - npm version --no-git-tag-version {{ .Version }}
    - npm pack

builds:
  - id: jailoc
    main: ./cmd/jailoc
    binary: jailoc
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    env:
      - CGO_ENABLED=0

archives:
  - id: jailoc
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: checksums.txt
  algorithm: sha256

changelog:
  disable: true

release:
  disable: false
  draft: false
  mode: append
  use_existing_draft: true
  github:
    owner: seznam
    name: jailoc
  extra_files:
    - glob: "seznam-jailoc-*.tgz"

snapshot:
  version_template: "{{ incpatch .Version }}-next"
